spring.application.name=student-placement-tracker

# Server port (moved to 8081 to avoid conflict with old server)
server.port=8081

# (Optional) future place for DB config if you move to Spring Data

